[project]
name = "mula"
version = "0.1.0"
description = "Beginner-friendly machine learning resource"
readme = "README.md"
requires-python = ">= 3.12"
license = {file = "LICENSE"}

classifiers = [  # List of https://pypi.org/classifiers/
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Education",
]
dependencies = [
    "chex==0.1.91",
    "grain==0.2.16",
    "jax==0.10.1",
    "flax==0.12.7",
    "ml_dtypes==0.5.4",
    "optax==0.2.8",
    "orbax-checkpoint==0.12.0",
    "orbax-export==0.0.8",
    "pgx>=2.0.0",
    "mctx",
    "matplotlib",
    "omegaconf",
    "pydantic",
]

[project.urls]
repository = "https://github.com/xrhd/mula"

[project.optional-dependencies]
# Development deps (unittest, linting, formating,...)
# Installed through `pip install -e .[dev]`
dev = [
    "pylint>=2.6.0",
    "pyink",
]

[tool.pyink]
# Formatting configuration to follow Google style-guide
line-length = 80
unstable = true
pyink-indentation = 2
pyink-use-majority-quotes = true

[tool.setuptools.packages]
find = {}

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
